---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: store-front
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: store-front
  policy:
    semver:
      range: '>=2.0.0'
